module.exports = {
  id: 25577585,
  id_str: '25577585',
  name: 'Fl\u00e1vio Dino \ud83c\udde7\ud83c\uddf7',
  screen_name: 'FlavioDino',
  location: 'Maranh\u00e3o',
  profile_location: null,
  description:
    'Governador do Maranh\u00e3o. Advogado, mestre em Direito P\u00fablico (UFPE) e professor de Direito na UFMA. Foi juiz federal (1994/2006) e deputado federal (2007/2010)',
  url: 'https://t.co/YG2zI5rUtp',
  entities: {
    url: {
      urls: [
        {
          url: 'https://t.co/YG2zI5rUtp',
          expanded_url: 'http://www.flaviodino.com.br',
          display_url: 'flaviodino.com.br',
          indices: [0, 23],
        },
      ],
    },
    description: { urls: [] },
  },
  protected: false,
  followers_count: 629518,
  friends_count: 698,
  listed_count: 1269,
  created_at: 'Fri Mar 20 21:14:30 +0000 2009',
  favourites_count: 39036,
  utc_offset: null,
  time_zone: null,
  geo_enabled: true,
  verified: true,
  statuses_count: 66922,
  lang: null,
  status: {
    created_at: 'Sun Jun 27 23:35:19 +0000 2021',
    id: 1409294302224785413,
    id_str: '1409294302224785413',
    text:
      'Arraiais da Vacina\u00e7\u00e3o em Ros\u00e1rio, Barra do Corda, Penalva e Riach\u00e3o: mais 12.700 pessoas vacinadas. Mutir\u00f5es do\u2026 https://t.co/pJLvJKbx3b',
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/pJLvJKbx3b',
          expanded_url: 'https://twitter.com/i/web/status/1409294302224785413',
          display_url: 'twitter.com/i/web/status/1\u2026',
          indices: [113, 136],
        },
      ],
    },
    source:
      '\u003ca href="http://twitter.com/download/iphone" rel="nofollow"\u003eTwitter for iPhone\u003c/a\u003e',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 12,
    favorite_count: 202,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'pt',
  },
  contributors_enabled: false,
  is_translator: false,
  is_translation_enabled: false,
  profile_background_color: 'C7C7C7',
  profile_background_image_url:
    'http://abs.twimg.com/images/themes/theme1/bg.png',
  profile_background_image_url_https:
    'https://abs.twimg.com/images/themes/theme1/bg.png',
  profile_background_tile: false,
  profile_image_url:
    'http://pbs.twimg.com/profile_images/1409291507258073093/2ImdZpcR_normal.jpg',
  profile_image_url_https:
    'https://pbs.twimg.com/profile_images/1409291507258073093/2ImdZpcR_normal.jpg',
  profile_banner_url:
    'https://pbs.twimg.com/profile_banners/25577585/1613491800',
  profile_link_color: '8F0606',
  profile_sidebar_border_color: 'FFFFFF',
  profile_sidebar_fill_color: 'EDEDED',
  profile_text_color: '1A0A0F',
  profile_use_background_image: true,
  has_extended_profile: true,
  default_profile: false,
  default_profile_image: false,
  following: true,
  follow_request_sent: false,
  notifications: false,
  translator_type: 'none',
  withheld_in_countries: [],
}
